### ISSUE TITLE
[Bug] Spritesheets are not assembling from the target folder

### ISSUE THREAD

**Issue by NickRimer03** [pencil-js/spritesheet-cli#1]
#### Information
 - The package and version you used: _@pencil.js/spritesheet-cli v1.5.0_
 - OS: _Ubuntu 20.04_
 - Node version: _14.16.0_
 - NPM version: _6.14.11_

#### Description
Spritesheet creation process works only when sprites are in default root folder.

#### Reproduce by 
```js
import { exec } from "child_process";

exec("spritesheet *.png -c ./assets/images/fire -o ./assets/atlas");
```

Output:
```
Packing 27 files ...
index.js:18 Error: ENOENT: no such file or directory, open 'package.json'
```

And there is more strange thing.
I have 27 png's in `./assets/images/fire` folder.
But! When I copied 3 png's into root folder to test default input code from above works strange:

Output:
```
Packing 3 files ...
index.js:18 Error: ENOENT: no such file or directory, open 'package.json'
```
*3 files!* But input folder is set as `./assets/images/fire` where 27 files are...

#### This code works
```js
import { exec } from "child_process";

exec("spritesheet *.png -o ./assets/atlas");
```

Output:
```
Packing 3 files ...
✔️ Image created
✔️ JSON created
```

#### My package.json
```json
{
  "name": "spritesheet-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "app": "node app.js",
    "app:cli": "node app-cli.js"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "type": "module",
  "devDependencies": {
    "@pencil.js/spritesheet-cli": "^1.5.0",
    "prettier": "^2.2.1"
  }
}
```

#### What I've tried to do
- `rm -rf ./node_modules && npm i`
- deleting `package-lock.json`

**Comment by GMartigny** [comment]
Hi,
This issue stem from the version 1.5.0 of spritesheet. I just pushed a patch that fix it (1.5.1).

Running `npm update` should do the trick.

**Comment by NickRimer03** [comment]
Hi, seems `@pencil.js/spritesheet-cli` still installing 1.5.0 version of `@pencil.js/spritesheet` package.

```
$ npm ls @pencil.js/spritesheet
spritesheet-test@1.0.0 /home/master/projects/spritesheet-test
└─┬ @pencil.js/spritesheet-cli@1.5.0
  └── @pencil.js/spritesheet@1.5.0 
```

**Tried:**
- `npm update`
- `rm -rf ./node_modules && npm i`

**Comment by GMartigny** [comment]
`npm update` should take care of updating to the latest `@pencil.js/spritesheet` (1.5.1).
Maybe try to delete your `package-lock.json` beforehand.
If you still have trouble after that, you can force it by running `npm install -D @pencil.js/spritesheet@1.5.1`.

**Comment by NickRimer03** [comment]
Ah, thank you. Forgot to delete `package-lock.json`.
Strange, but `npm update` not helped after that. But everything's good after re-installing modules :)

Thank you. Problem solved!

P.S. Will be there a some option to use different json types for different platforms, i.e. pixi, phaser etc.?
'Cause your module is freaking good in doing spritesheets, will be good to see its upgraded functionality.

**Comment by GMartigny** [comment]
Glad it worked.

Thanks for the kind words. As far as I know, Spritesheet output is compatible with most of game engine (Pixi, Phaser and of course Pencil.js 😉). If this is not the case, open a new issue and I'll look into it.
